// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKL0Fh28dpk0Rmfm7-qBGJsHfB271jNc',
    appId: '1:1010120152068:web:1ce8ca2baf2de38068d151',
    messagingSenderId: '1010120152068',
    projectId: 'shopapp-53269',
    authDomain: 'shopapp-53269.firebaseapp.com',
    storageBucket: 'shopapp-53269.appspot.com',
    measurementId: 'G-G5W3M18LS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3gFX6C5cj3C8yjEyV0jXCek8ZPQM4Ks',
    appId: '1:1010120152068:android:5e15ba49fbe3842b68d151',
    messagingSenderId: '1010120152068',
    projectId: 'shopapp-53269',
    storageBucket: 'shopapp-53269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRmIGi0hpEa-LYC7wZLs1MPfyW6L0-7iY',
    appId: '1:1010120152068:ios:491b3615fcf337cc68d151',
    messagingSenderId: '1010120152068',
    projectId: 'shopapp-53269',
    storageBucket: 'shopapp-53269.appspot.com',
    iosBundleId: 'com.example.appBanHang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRmIGi0hpEa-LYC7wZLs1MPfyW6L0-7iY',
    appId: '1:1010120152068:ios:319e65b59631bc0868d151',
    messagingSenderId: '1010120152068',
    projectId: 'shopapp-53269',
    storageBucket: 'shopapp-53269.appspot.com',
    iosBundleId: 'com.example.appBanHang.RunnerTests',
  );
}
